name=BareMetalHAL
version=0.1.0
author=Dan Mowehhuk <danmowehhuk@gmail.com>
maintainer=Dan Mowehhuk <danmowehhuk@gmail.com>
sentence=Hardware abstraction layer for non-Arduino embedded targets
paragraph=Provides backends for libraries built with -DNO_ARDUINO
category=Other
url=https://github.com/danmowehhuk/BareMetalHAL
architectures=*
includes=BareMetalHAL.h
license=BSD
